name: fire_atlas_editor
description: Editor to create Fire atlas textures

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  file_selector: ^0.9.2+2
  file_selector_linux: ^0.9.1
  file_selector_macos: ^0.9.0+4
  file_selector_windows: ^0.9.1+4
  flame: ^1.6.0
  flame_fire_atlas: ^1.3.3
  flame_lint: ^0.2.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.17
  slices: ^0.0.2
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
