name: flame_fire_atlas
description: Easy to use texture atlases for the flame engine created with the fire atlas editor
version: 0.0.4
homepage: https://github.com/flame-engine/fire-atlas/tree/master/flame_fire_atlas

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: 1.0.0-rc5
  archive: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
